### ISSUE TITLE
添加/修改代码的时候, 偶尔会报500错误

### ISSUE THREAD

**Issue by darth30joker** [DoubleCiti/daimaduan.com#53]
```
127.0.0.1 - - [05/Nov/2015 23:40:26] "GET /paste/69d3f71897/edit HTTP/1.1" 200 8496
Traceback (most recent call last):
  File "/Users/davidx/.virtualenvs/daimaduan/lib/python2.7/site-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/Users/davidx/.virtualenvs/daimaduan/lib/python2.7/site-packages/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "/Users/davidx/.virtualenvs/daimaduan/lib/python2.7/site-packages/bottle_login.py", line 33, in wrapper
    return callback(*args, **kwargs)
  File "/Users/davidx/Projects/daimaduan.com/daimaduan/jinja_ext.py", line 72, in wrapper
    return callback(*args, **kwargs)
  File "/Users/davidx/.virtualenvs/daimaduan/lib/python2.7/site-packages/bottle_login.py", line 62, in wrapper
    return callback(*args, **kwargs)
  File "/Users/davidx/.virtualenvs/daimaduan/lib/python2.7/site-packages/bottle.py", line 3619, in wrapper
    return template(tpl_name, **tplvars)
  File "/Users/davidx/.virtualenvs/daimaduan/lib/python2.7/site-packages/bottle.py", line 3595, in template
    return TEMPLATES[tplid].render(kwargs)
  File "/Users/davidx/.virtualenvs/daimaduan/lib/python2.7/site-packages/bottle.py", line 3322, in render
    return self.tpl.render(**_defaults)
  File "/Users/davidx/.virtualenvs/daimaduan/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/davidx/.virtualenvs/daimaduan/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 1, in top-level template code
  File "<template>", line 22, in top-level template code
  File "<template>", line 11, in block "content"
  File "/Users/davidx/.virtualenvs/daimaduan/lib/python2.7/site-packages/wtforms/fields/core.py", line 149, in __call__
    return self.meta.render_field(self, kwargs)
  File "/Users/davidx/.virtualenvs/daimaduan/lib/python2.7/site-packages/wtforms/meta.py", line 53, in render_field
    return field.widget(field, **render_kw)
  File "/Users/davidx/.virtualenvs/daimaduan/lib/python2.7/site-packages/wtforms/widgets/core.py", line 157, in __call__
    kwargs['value'] = field._value()
  File "/Users/davidx/.virtualenvs/daimaduan/lib/python2.7/site-packages/wtforms/fields/core.py", line 529, in _value
    return text_type(self.data) if self.data is not None else ''
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 0: ordinal not in range(128)
127.0.0.1 - - [05/Nov/2015 23:40:41] "POST /paste/69d3f71897/edit HTTP/1.1" 500 4669
```

**Comment by darth30joker** [comment]
只添加一个代码段或者修改一个代码段的时候, 不会出现500错误

**Comment by darth30joker** [comment]
https://github.com/DoubleCiti/daimaduan.com/pull/66
